In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])  



![](http://jalammar.github.io/images/numpy/create-numpy-array-1.png)

In [5]:
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


![](http://jalammar.github.io/images/numpy/numpy-array-create-2d.png)

![](http://jalammar.github.io/images/numpy/numpy-3d-array.png)

In [6]:
b = np.array([[1,2],[3,4]]) 
print(b)

[[1 2]
 [3 4]]


In [7]:
print(b.shape)

(2, 2)


![](http://jalammar.github.io/images/numpy/create-numpy-array-ones-zeros-random.png)

![](http://jalammar.github.io/images/numpy/numpy-matrix-ones-zeros-random.png)

![](http://jalammar.github.io/images/numpy/numpy-3d-array-creation.png)

In [8]:
a = np.zeros((2,2))  
print(a)

[[0. 0.]
 [0. 0.]]


In [9]:
b = np.ones((1,2))  
print(b)

[[1. 1.]]


In [10]:
c = np.full((2,2), 7) 
print(c)

[[7 7]
 [7 7]]


In [11]:
e = np.random.random((2,2)) 
print(e)

[[0.05598676 0.06124249]
 [0.93403281 0.41305955]]


In [12]:
print("Size:", e.size)

Size: 4


In [13]:
print("Itemsize:", e.itemsize)

Itemsize: 8


In [14]:
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a)
reshaped = a.reshape(3, 2)
print(reshaped)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [15]:
f = np.arange(10,50,5)  
print(f)

[10 15 20 25 30 35 40 45]


In [16]:
g = np.linspace(0., 1., num=5)
print(g)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(f"{a=}\n")
print(f"{b=}\n")
np.vstack((a,b))

a=array([1, 2, 3])

b=array([4, 5, 6])



array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.array([[7], [8], [9]])
b = np.array([[4], [5], [6]])

print(f"{a=}\n")
print(f"{b=}\n")
np.hstack((a,b))

a=array([[7],
       [8],
       [9]])

b=array([[4],
       [5],
       [6]])



array([[7, 4],
       [8, 5],
       [9, 6]])

In [16]:
py_list = [1, 2, 3, 4]
np_array = np.array([1, 2, 3, 4])
print(py_list * 2)
print(np_array * 2)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


### Індекси


Numpy пропонує кілька способів індексування в масиви.

Ми можемо індексувати та використовувати розділення `slice` для масивів numpy усіма способами, як зі списками Python:

![](http://jalammar.github.io/images/numpy/numpy-array-slice.png)

І ви можете індексувати та розділяти масиви numpy у кількох вимірах. Якщо розрізати масив із кількома вимірами, ви повинні вказати зріз для кожного виміру:

![](http://jalammar.github.io/images/numpy/numpy-matrix-indexing.png)

Під час роботи з масивами numpy часто корисно отримати *індекси* (а не лише значення) елементів масиву, які відповідають певним умовам. Є кілька функцій numpy, які ви точно захочете запам’ятати:

-   [`argmax`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) (індекс максимального елементу)
-   [`argmin`](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html) (індекс мінімального елементу)
-   [`argsort`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) (відсортований список індексів за значенням елемента в порядку зростання)
-   [`where`](https://numpy.org/doc/stable/reference/generated/numpy.where.html) (індекси елементів, які відповідають певній умові)

In [6]:
a = np.array([1, 8, 9, -3, 2, 4, 7, 9])

print(np.argmax(a))

print(np.argmin(a))

print(np.argsort(a))

print(np.argsort(a)[::-1])

print(np.where(a > 5)[0])

2
3
[3 0 4 5 6 1 2 7]
[7 2 1 6 5 4 0 3]
[1 2 6 7]


### Типи даних

In [17]:
x = np.array([1, 2])  
y = np.array([1.0, 2.0])  
z = np.array([1, 2], dtype=np.int64)  

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


### Дії з масивами

In [ ]:
a = np.random.random(10000000)

In [ ]:
%%time
x = np.sum(a)

CPU times: user 10.5 ms, sys: 0 ns, total: 10.5 ms
Wall time: 22.7 ms


In [ ]:
%%time
x = 0
for element in a:
  x = x + element

CPU times: user 1.89 s, sys: 3.3 ms, total: 1.9 s
Wall time: 1.91 s



Наприклад, ви можете виконати поелементне підсумовування двох масивів за допомогою оператора + або функції `add()`.

![](http://jalammar.github.io/images/numpy/numpy-arrays-adding-1.png)

![](http://jalammar.github.io/images/numpy/numpy-matrix-arithmetic.png)

In [18]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


І це також працює для інших операцій, а не лише для додавання:

![](http://jalammar.github.io/images/numpy/numpy-array-subtract-multiply-divide.png)

In [20]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
print(x * y)
print(np.multiply(x, y))

In [ ]:
print(x / y)
print(np.divide(x, y))

In [21]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


![](http://jalammar.github.io/images/numpy/numpy-matrix-dot-product-1.png)

In [23]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

219
219


![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-1.png)

In [25]:
x = np.array([[1, 2], [3, 4], [5, 6]])

print(np.max(x)) 
print(np.min(x))  
print(np.sum(x))  

6
1
21


![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-4.png)

In [7]:
x = np.array([[1, 2], [5, 3], [4, 6]])

print(np.max(x, axis=0))  
print(np.max(x, axis=1))  

[5 6]
[2 5 6]
